package io.github.springsongs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import io.github.springsongs.domain.SpringActVacation;
import io.github.springsongs.dto.SpringActVacationDTO;

@Mapper
public interface SpringActVacationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_vacation
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_vacation
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    int insert(SpringActVacation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_vacation
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    SpringActVacation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_vacation
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    List<SpringActVacation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_vacation
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    int updateByPrimaryKey(SpringActVacation record);

	SpringActVacation findByProcessInstanceId(@Param("procInstanceId") String procInstanceId);

	List<SpringActVacation> listByPage(@Param("record") SpringActVacationDTO record);

	void setDelete(@Param("ids") List<String> ids);
}