package io.github.springsongs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import io.github.springsongs.domain.SpringActCategory;
import io.github.springsongs.dto.SpringActCategoryDTO;

@Mapper
public interface SpringActCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_category
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_category
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    int insert(SpringActCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_category
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    SpringActCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_category
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    List<SpringActCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_act_category
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    int updateByPrimaryKey(SpringActCategory record);

	SpringActCategory getByCode(@Param("categoryCode") String categoryCode);

	List<SpringActCategory> listByPage(@Param("record") SpringActCategoryDTO record);

	List<SpringActCategory> listAll();

	void setDelete(@Param("ids") List<String> ids);
}