package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringParameter;
import java.util.List;

public interface SpringParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_parameter
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_parameter
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_parameter
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringParameter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_parameter
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringParameter> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_parameter
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringParameter record);
}