package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringSystem;
import java.util.List;

public interface SpringSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_system
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_system
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_system
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringSystem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_system
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringSystem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_system
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringSystem record);
}