package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringLoginLog;
import java.util.List;

public interface SpringLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_login_log
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_login_log
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_login_log
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringLoginLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_login_log
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringLoginLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_login_log
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringLoginLog record);
}