package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringArticleCategory;
import java.util.List;

public interface SpringArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringArticleCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringArticleCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringArticleCategory record);
}