package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringContact;
import java.util.List;

public interface SpringContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_contact
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_contact
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_contact
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringContact selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_contact
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringContact> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_contact
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringContact record);
}