package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringFriendLink;
import java.util.List;

public interface SpringFriendLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringFriendLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringFriendLink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringFriendLink> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringFriendLink record);
}