package org.authority.domain;

import java.util.Date;

public class ApiSecurity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.appkey
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String appkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.appsecurity
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String appsecurity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Integer sortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean enableEdit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean enableDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_security.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.id
     *
     * @return the value of api_security.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.id
     *
     * @param id the value for api_security.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.appkey
     *
     * @return the value of api_security.appkey
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.appkey
     *
     * @param appkey the value for api_security.appkey
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey == null ? null : appkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.appsecurity
     *
     * @return the value of api_security.appsecurity
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getAppsecurity() {
        return appsecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.appsecurity
     *
     * @param appsecurity the value for api_security.appsecurity
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setAppsecurity(String appsecurity) {
        this.appsecurity = appsecurity == null ? null : appsecurity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.sort_code
     *
     * @return the value of api_security.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.sort_code
     *
     * @param sortCode the value for api_security.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.enable_edit
     *
     * @return the value of api_security.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getEnableEdit() {
        return enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.enable_edit
     *
     * @param enableEdit the value for api_security.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setEnableEdit(Boolean enableEdit) {
        this.enableEdit = enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.enable_delete
     *
     * @return the value of api_security.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getEnableDelete() {
        return enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.enable_delete
     *
     * @param enableDelete the value for api_security.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setEnableDelete(Boolean enableDelete) {
        this.enableDelete = enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.deleted_flag
     *
     * @return the value of api_security.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.deleted_flag
     *
     * @param deletedFlag the value for api_security.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.created_user_id
     *
     * @return the value of api_security.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.created_user_id
     *
     * @param createdUserId the value for api_security.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.created_by
     *
     * @return the value of api_security.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.created_by
     *
     * @param createdBy the value for api_security.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.created_on
     *
     * @return the value of api_security.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.created_on
     *
     * @param createdOn the value for api_security.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.created_ip
     *
     * @return the value of api_security.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.created_ip
     *
     * @param createdIp the value for api_security.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp == null ? null : createdIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.updated_user_id
     *
     * @return the value of api_security.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.updated_user_id
     *
     * @param updatedUserId the value for api_security.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.updated_by
     *
     * @return the value of api_security.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.updated_by
     *
     * @param updatedBy the value for api_security.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.updated_on
     *
     * @return the value of api_security.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.updated_on
     *
     * @param updatedOn the value for api_security.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_security.updated_ip
     *
     * @return the value of api_security.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_security.updated_ip
     *
     * @param updatedIp the value for api_security.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp == null ? null : updatedIp.trim();
    }
}