package org.authority.domain;

import java.util.Date;

public class DictionaryDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.dictionary_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String dictionaryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.parent_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.item_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String detailCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.item_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String detailName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.item_value
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String detailValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.item_desc
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Integer sortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean enableEdit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean enableDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_detail.child_ids
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String childIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.id
     *
     * @return the value of dictionary_detail.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.id
     *
     * @param id the value for dictionary_detail.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.dictionary_code
     *
     * @return the value of dictionary_detail.dictionary_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getDictionaryCode() {
        return dictionaryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.dictionary_code
     *
     * @param dictionaryCode the value for dictionary_detail.dictionary_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDictionaryCode(String dictionaryCode) {
        this.dictionaryCode = dictionaryCode == null ? null : dictionaryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.parent_id
     *
     * @return the value of dictionary_detail.parent_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.parent_id
     *
     * @param parentId the value for dictionary_detail.parent_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.item_code
     *
     * @return the value of dictionary_detail.item_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getDetailCode() {
        return detailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.item_code
     *
     * @param itemCode the value for dictionary_detail.item_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDetailCode(String detailCode) {
        this.detailCode = detailCode == null ? null : detailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.item_name
     *
     * @return the value of dictionary_detail.item_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getDetailName() {
        return detailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.item_name
     *
     * @param itemName the value for dictionary_detail.item_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDetailName(String detailName) {
        this.detailName = detailName == null ? null : detailName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.item_value
     *
     * @return the value of dictionary_detail.item_value
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getDetailValue() {
        return detailValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.item_value
     *
     * @param itemValue the value for dictionary_detail.item_value
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDetailValue(String detailValue) {
        this.detailValue = detailValue == null ? null : detailValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.item_desc
     *
     * @return the value of dictionary_detail.item_desc
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.item_desc
     *
     * @param itemDesc the value for dictionary_detail.item_desc
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.sort_code
     *
     * @return the value of dictionary_detail.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.sort_code
     *
     * @param sortCode the value for dictionary_detail.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.enable_edit
     *
     * @return the value of dictionary_detail.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getEnableEdit() {
        return enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.enable_edit
     *
     * @param enableEdit the value for dictionary_detail.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setEnableEdit(Boolean enableEdit) {
        this.enableEdit = enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.enable_delete
     *
     * @return the value of dictionary_detail.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getEnableDelete() {
        return enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.enable_delete
     *
     * @param enableDelete the value for dictionary_detail.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setEnableDelete(Boolean enableDelete) {
        this.enableDelete = enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.deleted_flag
     *
     * @return the value of dictionary_detail.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.deleted_flag
     *
     * @param deletedFlag the value for dictionary_detail.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.created_user_id
     *
     * @return the value of dictionary_detail.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.created_user_id
     *
     * @param createdUserId the value for dictionary_detail.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.created_by
     *
     * @return the value of dictionary_detail.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.created_by
     *
     * @param createdBy the value for dictionary_detail.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.created_on
     *
     * @return the value of dictionary_detail.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.created_on
     *
     * @param createdOn the value for dictionary_detail.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.created_ip
     *
     * @return the value of dictionary_detail.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.created_ip
     *
     * @param createdIp the value for dictionary_detail.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp == null ? null : createdIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.updated_user_id
     *
     * @return the value of dictionary_detail.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.updated_user_id
     *
     * @param updatedUserId the value for dictionary_detail.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.updated_by
     *
     * @return the value of dictionary_detail.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.updated_by
     *
     * @param updatedBy the value for dictionary_detail.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.updated_on
     *
     * @return the value of dictionary_detail.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.updated_on
     *
     * @param updatedOn the value for dictionary_detail.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.updated_ip
     *
     * @return the value of dictionary_detail.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.updated_ip
     *
     * @param updatedIp the value for dictionary_detail.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp == null ? null : updatedIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_detail.child_ids
     *
     * @return the value of dictionary_detail.child_ids
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getChildIds() {
        return childIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_detail.child_ids
     *
     * @param childIds the value for dictionary_detail.child_ids
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setChildIds(String childIds) {
        this.childIds = childIds == null ? null : childIds.trim();
    }
}