package org.authority.domain;

import java.util.Date;

public class LoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.description
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.id
     *
     * @return the value of login_log.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.id
     *
     * @param id the value for login_log.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.description
     *
     * @return the value of login_log.description
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.description
     *
     * @param description the value for login_log.description
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.created_user_id
     *
     * @return the value of login_log.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.created_user_id
     *
     * @param createdUserId the value for login_log.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.created_by
     *
     * @return the value of login_log.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.created_by
     *
     * @param createdBy the value for login_log.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.created_on
     *
     * @return the value of login_log.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.created_on
     *
     * @param createdOn the value for login_log.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.created_ip
     *
     * @return the value of login_log.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.created_ip
     *
     * @param createdIp the value for login_log.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp == null ? null : createdIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.updated_user_id
     *
     * @return the value of login_log.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.updated_user_id
     *
     * @param updatedUserId the value for login_log.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.updated_by
     *
     * @return the value of login_log.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.updated_by
     *
     * @param updatedBy the value for login_log.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.updated_on
     *
     * @return the value of login_log.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.updated_on
     *
     * @param updatedOn the value for login_log.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.updated_ip
     *
     * @return the value of login_log.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.updated_ip
     *
     * @param updatedIp the value for login_log.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp == null ? null : updatedIp.trim();
    }
}