package org.authority.domain;

import java.util.Date;

public class ModuleRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.module_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    private String moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.role_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.created_user_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.created_by
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.created_on
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.created_ip
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    private String createdIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.id
     *
     * @return the value of module_role.id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.id
     *
     * @param id the value for module_role.id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.module_id
     *
     * @return the value of module_role.module_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.module_id
     *
     * @param moduleId the value for module_role.module_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.role_id
     *
     * @return the value of module_role.role_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.role_id
     *
     * @param roleId the value for module_role.role_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.created_user_id
     *
     * @return the value of module_role.created_user_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.created_user_id
     *
     * @param createdUserId the value for module_role.created_user_id
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.created_by
     *
     * @return the value of module_role.created_by
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.created_by
     *
     * @param createdBy the value for module_role.created_by
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.created_on
     *
     * @return the value of module_role.created_on
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.created_on
     *
     * @param createdOn the value for module_role.created_on
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.created_ip
     *
     * @return the value of module_role.created_ip
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.created_ip
     *
     * @param createdIp the value for module_role.created_ip
     *
     * @mbg.generated Thu Nov 14 16:27:48 CST 2019
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp == null ? null : createdIp.trim();
    }
}