package org.authority.domain;

import java.util.Date;

public class Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.title
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.form_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String formName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.menu_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean menuFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.vue_icon
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String vueIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.vue_url
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String vueUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.angular_icon
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String angularIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.angular_url
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String angularUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.parent_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.parent_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Integer sortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean enableEdit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean enableDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.system_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.id
     *
     * @return the value of module.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.id
     *
     * @param id the value for module.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.code
     *
     * @return the value of module.code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.code
     *
     * @param code the value for module.code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.title
     *
     * @return the value of module.title
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.title
     *
     * @param title the value for module.title
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.form_name
     *
     * @return the value of module.form_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getFormName() {
        return formName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.form_name
     *
     * @param formName the value for module.form_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setFormName(String formName) {
        this.formName = formName == null ? null : formName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.menu_flag
     *
     * @return the value of module.menu_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getMenuFlag() {
        return menuFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.menu_flag
     *
     * @param menuFlag the value for module.menu_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setMenuFlag(Boolean menuFlag) {
        this.menuFlag = menuFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.vue_icon
     *
     * @return the value of module.vue_icon
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getVueIcon() {
        return vueIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.vue_icon
     *
     * @param vueIcon the value for module.vue_icon
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setVueIcon(String vueIcon) {
        this.vueIcon = vueIcon == null ? null : vueIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.vue_url
     *
     * @return the value of module.vue_url
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getVueUrl() {
        return vueUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.vue_url
     *
     * @param vueUrl the value for module.vue_url
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setVueUrl(String vueUrl) {
        this.vueUrl = vueUrl == null ? null : vueUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.angular_icon
     *
     * @return the value of module.angular_icon
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getAngularIcon() {
        return angularIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.angular_icon
     *
     * @param angularIcon the value for module.angular_icon
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setAngularIcon(String angularIcon) {
        this.angularIcon = angularIcon == null ? null : angularIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.angular_url
     *
     * @return the value of module.angular_url
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getAngularUrl() {
        return angularUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.angular_url
     *
     * @param angularUrl the value for module.angular_url
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setAngularUrl(String angularUrl) {
        this.angularUrl = angularUrl == null ? null : angularUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.parent_id
     *
     * @return the value of module.parent_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.parent_id
     *
     * @param parentId the value for module.parent_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.parent_name
     *
     * @return the value of module.parent_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.parent_name
     *
     * @param parentName the value for module.parent_name
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.sort_code
     *
     * @return the value of module.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.sort_code
     *
     * @param sortCode the value for module.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.enable_edit
     *
     * @return the value of module.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getEnableEdit() {
        return enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.enable_edit
     *
     * @param enableEdit the value for module.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setEnableEdit(Boolean enableEdit) {
        this.enableEdit = enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.enable_delete
     *
     * @return the value of module.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getEnableDelete() {
        return enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.enable_delete
     *
     * @param enableDelete the value for module.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setEnableDelete(Boolean enableDelete) {
        this.enableDelete = enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.deleted_flag
     *
     * @return the value of module.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.deleted_flag
     *
     * @param deletedFlag the value for module.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.system_id
     *
     * @return the value of module.system_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.system_id
     *
     * @param systemId the value for module.system_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId == null ? null : systemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.created_user_id
     *
     * @return the value of module.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.created_user_id
     *
     * @param createdUserId the value for module.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.created_by
     *
     * @return the value of module.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.created_by
     *
     * @param createdBy the value for module.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.created_on
     *
     * @return the value of module.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.created_on
     *
     * @param createdOn the value for module.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.created_ip
     *
     * @return the value of module.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.created_ip
     *
     * @param createdIp the value for module.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp == null ? null : createdIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.updated_user_id
     *
     * @return the value of module.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.updated_user_id
     *
     * @param updatedUserId the value for module.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.updated_by
     *
     * @return the value of module.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.updated_by
     *
     * @param updatedBy the value for module.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.updated_on
     *
     * @return the value of module.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.updated_on
     *
     * @param updatedOn the value for module.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.updated_ip
     *
     * @return the value of module.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.updated_ip
     *
     * @param updatedIp the value for module.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp == null ? null : updatedIp.trim();
    }
}