package org.authority.domain;

import java.util.Date;

public class Parameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.title
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.content
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Integer sortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean enableEdit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean enableDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Boolean deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.id
     *
     * @return the value of parameter.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.id
     *
     * @param id the value for parameter.id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.code
     *
     * @return the value of parameter.code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.code
     *
     * @param code the value for parameter.code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.title
     *
     * @return the value of parameter.title
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.title
     *
     * @param title the value for parameter.title
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.content
     *
     * @return the value of parameter.content
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.content
     *
     * @param content the value for parameter.content
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.sort_code
     *
     * @return the value of parameter.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.sort_code
     *
     * @param sortCode the value for parameter.sort_code
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.enable_edit
     *
     * @return the value of parameter.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getEnableEdit() {
        return enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.enable_edit
     *
     * @param enableEdit the value for parameter.enable_edit
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setEnableEdit(Boolean enableEdit) {
        this.enableEdit = enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.enable_delete
     *
     * @return the value of parameter.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getEnableDelete() {
        return enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.enable_delete
     *
     * @param enableDelete the value for parameter.enable_delete
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setEnableDelete(Boolean enableDelete) {
        this.enableDelete = enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.deleted_flag
     *
     * @return the value of parameter.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.deleted_flag
     *
     * @param deletedFlag the value for parameter.deleted_flag
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.created_user_id
     *
     * @return the value of parameter.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.created_user_id
     *
     * @param createdUserId the value for parameter.created_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.created_by
     *
     * @return the value of parameter.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.created_by
     *
     * @param createdBy the value for parameter.created_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.created_on
     *
     * @return the value of parameter.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.created_on
     *
     * @param createdOn the value for parameter.created_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.created_ip
     *
     * @return the value of parameter.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.created_ip
     *
     * @param createdIp the value for parameter.created_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp == null ? null : createdIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.updated_user_id
     *
     * @return the value of parameter.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.updated_user_id
     *
     * @param updatedUserId the value for parameter.updated_user_id
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.updated_by
     *
     * @return the value of parameter.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.updated_by
     *
     * @param updatedBy the value for parameter.updated_by
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.updated_on
     *
     * @return the value of parameter.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.updated_on
     *
     * @param updatedOn the value for parameter.updated_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.updated_ip
     *
     * @return the value of parameter.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.updated_ip
     *
     * @param updatedIp the value for parameter.updated_ip
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp == null ? null : updatedIp.trim();
    }
}