package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringJobHistory;
import io.github.springsongs.dto.SpringJobHistoryDTO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SpringJobHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job_history
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job_history
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    int insert(SpringJobHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job_history
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    SpringJobHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job_history
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    List<SpringJobHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job_history
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    int updateByPrimaryKey(SpringJobHistory record);

	List<SpringJobHistory> listByPage(@Param("record") SpringJobHistoryDTO record);

	void setDelete(@Param("ids") List<String> ids);
}