package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringJob;
import io.github.springsongs.dto.SpringJobDTO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SpringJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    int insert(SpringJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    SpringJob selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    List<SpringJob> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_job
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    int updateByPrimaryKey(SpringJob record);

	List<SpringJob> listByPage(@Param("record") SpringJobDTO record);

	SpringJob findByGroupCodeAndTaskClassTitle(@Param("groupCode") String groupCode,@Param("taskClassName")  String taskClassName);
}