package org.authority.mapper;

import org.authority.domain.MemberSecurity;

import com.github.pagehelper.Page;

public interface BaseUserLogOnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buser_log_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buser_log_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insert(MemberSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buser_log_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insertSelective(MemberSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buser_log_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    MemberSecurity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buser_log_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKeySelective(MemberSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buser_log_on
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKey(MemberSecurity record);
    
    Page<MemberSecurity> ListByPage(MemberSecurity record);

	MemberSecurity findPwdByUserId(String userId);
}