package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.DictionaryDetail;

import com.github.pagehelper.Page;

public interface BaseDictionaryDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_detail
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_detail
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insert(DictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_detail
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insertSelective(DictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_detail
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    DictionaryDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_detail
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKeySelective(DictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_detail
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(DictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_detail
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKey(DictionaryDetail record);
    
    Page<DictionaryDetail> ListByPage(DictionaryDetail record);

	void setDeleted(@Param("ids") List<String> ids);
	
	void deleteByCode(@Param("dictionaryCode") String dictionaryCode);
	
	List<DictionaryDetail> listByCode(@Param("dictionaryCode") String dictionaryCode);
}