package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.Member;

import com.github.pagehelper.Page;

public interface BaseUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	Member selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKey(Member record);

	Page<Member> ListByPage(Member record);

	Member getByUserName(@Param("username") String username);

	List<Member> listUsersByIds(@Param("ids") List<String> ids);

	void setDeleted(@Param("ids") List<String> ids);

	Page<Member> listUserByRoleId(@Param("roleId") String roleId);

	
}