package org.authority.mapper;

import org.authority.domain.Attachment;

import com.github.pagehelper.Page;

public interface BaseFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    Attachment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKeySelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKey(Attachment record);
    
    
    Page<Attachment> ListByPage(Attachment record);
}