package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.Dictionary;
import org.authority.domain.Role;

import com.github.pagehelper.Page;

public interface BaseRoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	Role selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKey(Role record);

	Page<Role> ListByPage(Role record);

	List<Role> getRolesByUserId(@Param("userId") String userId);

	void setDeleted(@Param("ids") List<String> ids);

	List<Role> listInIds(@Param("ids") List<String> ids);

	Page<Role> listRolesByUserId(@Param("userId") String userId);
}