package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.ApiSecurity;

import com.github.pagehelper.Page;

public interface BaseApiSecurityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_security
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
   public int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_security
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
   public int insert(ApiSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_security
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
   public int insertSelective(ApiSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_security
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
   public  ApiSecurity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_security
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
   public int updateByPrimaryKeySelective(ApiSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_security
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
   public int updateByPrimaryKey(ApiSecurity record);

    
   public Page<ApiSecurity> ListByPage(ApiSecurity record);
   
   List<ApiSecurity> listAppSecuritysByIds(@Param("ids") List<String> ids);
	
	void setDeleted(@Param("ids") List<String> ids);
    
}