package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.BusinessCard;

import com.github.pagehelper.Page;

public interface BaseBusinessCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_card
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_card
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insert(BusinessCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_card
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insertSelective(BusinessCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_card
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    BusinessCard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_card
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKeySelective(BusinessCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_card
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKey(BusinessCard record);
    
    Page<BusinessCard> ListByPage(BusinessCard record);
    
    void setDeleted(@Param("ids") List<String> ids);
}