package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.MemberRole;

import com.github.pagehelper.Page;

public interface BaseUserRoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser_role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser_role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insert(MemberRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser_role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insertSelective(MemberRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser_role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	MemberRole selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser_role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKeySelective(MemberRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table buser_role
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKey(MemberRole record);

	Page<MemberRole> ListByPage(MemberRole record);
	
	void deleteByUserId(@Param(value = "userId") String userId);

	void saveAll(@Param(value = "baseUserRoleEntityList") List<MemberRole> baseUserRoleEntityList);

	void deleteByRoleId(@Param(value = "roleId") String roleId);
}