package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.Parameter;

import com.github.pagehelper.Page;

public interface BaseParameterMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table parameter
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table parameter
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insert(Parameter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table parameter
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insertSelective(Parameter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table parameter
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	Parameter selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table parameter
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKeySelective(Parameter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table parameter
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKey(Parameter record);

	Page<Parameter> ListByPage(Parameter record);

	List<Parameter> listParametersByIds(@Param("ids") List<String> ids);

	void setDeleted(@Param("ids") List<String> ids);
}