package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.System;

import com.github.pagehelper.Page;

public interface BaseSystemMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table system
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table system
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insert(System record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table system
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int insertSelective(System record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table system
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	System selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table system
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKeySelective(System record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table system
	 *
	 * @mbg.generated Thu Nov 07 15:40:12 CST 2019
	 */
	int updateByPrimaryKey(System record);

	Page<System> ListByPage(System record);

	List<System> listInIds(@Param("ids") List<String> ids);

	void setDeleted(@Param("ids") List<String> ids);

	List<System> listAll();
}