package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.Module;

import com.github.pagehelper.Page;

public interface BaseModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    Module selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKey(Module record);
    
    Page<Module> ListByPage(Module record);

    List<Module> listModuleByUserId(String userId);

	List<Module> getByParentId(@Param("parentId") String parentId,@Param("systemId")  String systemId);

	List<Module> getInParentId(@Param("ids") List<String> ids);
}