package org.authority.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.authority.domain.Aritlce;

import com.github.pagehelper.Page;

public interface BaseAritlceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aritlce
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aritlce
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insert(Aritlce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aritlce
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int insertSelective(Aritlce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aritlce
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    Aritlce selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aritlce
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKeySelective(Aritlce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aritlce
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Aritlce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aritlce
     *
     * @mbg.generated Thu Nov 07 15:40:12 CST 2019
     */
    int updateByPrimaryKey(Aritlce record);
    
    Page<Aritlce> ListByPage(Aritlce record);
    
    void setDeleted(@Param("ids") List<String> ids);
}