package io.github.springsongs.domain;

import java.util.Date;

public class SpringDictionaryDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.dictionary_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String dictionaryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.parent_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.detail_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String detailCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.detail_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String detailName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.detail_value
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String detailValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.description
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer sortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.enable_edit
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private boolean enableEdit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.enable_delete
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private boolean enableDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private boolean deletedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_dictionary_detail.child_ids
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String childIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.id
     *
     * @return the value of spring_dictionary_detail.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.id
     *
     * @param id the value for spring_dictionary_detail.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.dictionary_code
     *
     * @return the value of spring_dictionary_detail.dictionary_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getDictionaryCode() {
        return dictionaryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.dictionary_code
     *
     * @param dictionaryCode the value for spring_dictionary_detail.dictionary_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDictionaryCode(String dictionaryCode) {
        this.dictionaryCode = dictionaryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.parent_id
     *
     * @return the value of spring_dictionary_detail.parent_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.parent_id
     *
     * @param parentId the value for spring_dictionary_detail.parent_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.detail_code
     *
     * @return the value of spring_dictionary_detail.detail_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getDetailCode() {
        return detailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.detail_code
     *
     * @param detailCode the value for spring_dictionary_detail.detail_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDetailCode(String detailCode) {
        this.detailCode = detailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.detail_name
     *
     * @return the value of spring_dictionary_detail.detail_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getDetailName() {
        return detailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.detail_name
     *
     * @param detailName the value for spring_dictionary_detail.detail_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDetailName(String detailName) {
        this.detailName = detailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.detail_value
     *
     * @return the value of spring_dictionary_detail.detail_value
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getDetailValue() {
        return detailValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.detail_value
     *
     * @param detailValue the value for spring_dictionary_detail.detail_value
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDetailValue(String detailValue) {
        this.detailValue = detailValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.description
     *
     * @return the value of spring_dictionary_detail.description
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.description
     *
     * @param description the value for spring_dictionary_detail.description
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.sort_code
     *
     * @return the value of spring_dictionary_detail.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.sort_code
     *
     * @param sortCode the value for spring_dictionary_detail.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.enable_edit
     *
     * @return the value of spring_dictionary_detail.enable_edit
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public boolean getEnableEdit() {
        return enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.enable_edit
     *
     * @param enableEdit the value for spring_dictionary_detail.enable_edit
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setEnableEdit(boolean enableEdit) {
        this.enableEdit = enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.enable_delete
     *
     * @return the value of spring_dictionary_detail.enable_delete
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public boolean getEnableDelete() {
        return enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.enable_delete
     *
     * @param enableDelete the value for spring_dictionary_detail.enable_delete
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setEnableDelete(boolean enableDelete) {
        this.enableDelete = enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.deleted_status
     *
     * @return the value of spring_dictionary_detail.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public boolean getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.deleted_status
     *
     * @param deletedStatus the value for spring_dictionary_detail.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDeletedStatus(boolean deletedStatus) {
        this.deletedStatus = deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.created_user_id
     *
     * @return the value of spring_dictionary_detail.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.created_user_id
     *
     * @param createdUserId the value for spring_dictionary_detail.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.created_by
     *
     * @return the value of spring_dictionary_detail.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.created_by
     *
     * @param createdBy the value for spring_dictionary_detail.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.created_on
     *
     * @return the value of spring_dictionary_detail.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.created_on
     *
     * @param createdOn the value for spring_dictionary_detail.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.created_ip
     *
     * @return the value of spring_dictionary_detail.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.created_ip
     *
     * @param createdIp the value for spring_dictionary_detail.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.updated_user_id
     *
     * @return the value of spring_dictionary_detail.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.updated_user_id
     *
     * @param updatedUserId the value for spring_dictionary_detail.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.updated_by
     *
     * @return the value of spring_dictionary_detail.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.updated_by
     *
     * @param updatedBy the value for spring_dictionary_detail.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.updated_on
     *
     * @return the value of spring_dictionary_detail.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.updated_on
     *
     * @param updatedOn the value for spring_dictionary_detail.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.updated_ip
     *
     * @return the value of spring_dictionary_detail.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.updated_ip
     *
     * @param updatedIp the value for spring_dictionary_detail.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_dictionary_detail.child_ids
     *
     * @return the value of spring_dictionary_detail.child_ids
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getChildIds() {
        return childIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_dictionary_detail.child_ids
     *
     * @param childIds the value for spring_dictionary_detail.child_ids
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setChildIds(String childIds) {
        this.childIds = childIds;
    }
}