package io.github.springsongs.domain;

import java.util.Date;

public class SpringParameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.k
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String k;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.v
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String v;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer sortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.enable_edit
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private boolean enableEdit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.enable_delete
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private boolean enableDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Byte deletedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_parameter.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.id
     *
     * @return the value of spring_parameter.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.id
     *
     * @param id the value for spring_parameter.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.code
     *
     * @return the value of spring_parameter.code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.code
     *
     * @param code the value for spring_parameter.code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.k
     *
     * @return the value of spring_parameter.k
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.k
     *
     * @param k the value for spring_parameter.k
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setK(String k) {
        this.k = k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.v
     *
     * @return the value of spring_parameter.v
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getV() {
        return v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.v
     *
     * @param v the value for spring_parameter.v
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setV(String v) {
        this.v = v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.sort_code
     *
     * @return the value of spring_parameter.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.sort_code
     *
     * @param sortCode the value for spring_parameter.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.enable_edit
     *
     * @return the value of spring_parameter.enable_edit
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public boolean getEnableEdit() {
        return enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.enable_edit
     *
     * @param enableEdit the value for spring_parameter.enable_edit
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setEnableEdit(boolean enableEdit) {
        this.enableEdit = enableEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.enable_delete
     *
     * @return the value of spring_parameter.enable_delete
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public boolean getEnableDelete() {
        return enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.enable_delete
     *
     * @param enableDelete the value for spring_parameter.enable_delete
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setEnableDelete(boolean enableDelete) {
        this.enableDelete = enableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.deleted_status
     *
     * @return the value of spring_parameter.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Byte getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.deleted_status
     *
     * @param deletedStatus the value for spring_parameter.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDeletedStatus(Byte deletedStatus) {
        this.deletedStatus = deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.created_user_id
     *
     * @return the value of spring_parameter.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.created_user_id
     *
     * @param createdUserId the value for spring_parameter.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.created_by
     *
     * @return the value of spring_parameter.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.created_by
     *
     * @param createdBy the value for spring_parameter.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.created_on
     *
     * @return the value of spring_parameter.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.created_on
     *
     * @param createdOn the value for spring_parameter.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.created_ip
     *
     * @return the value of spring_parameter.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.created_ip
     *
     * @param createdIp the value for spring_parameter.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.updated_user_id
     *
     * @return the value of spring_parameter.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.updated_user_id
     *
     * @param updatedUserId the value for spring_parameter.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.updated_by
     *
     * @return the value of spring_parameter.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.updated_by
     *
     * @param updatedBy the value for spring_parameter.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.updated_on
     *
     * @return the value of spring_parameter.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.updated_on
     *
     * @param updatedOn the value for spring_parameter.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_parameter.updated_ip
     *
     * @return the value of spring_parameter.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_parameter.updated_ip
     *
     * @param updatedIp the value for spring_parameter.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }
}