package io.github.springsongs.domain;

import java.util.Date;

public class SpringContact {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.company
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.username
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.email
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.web
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String web;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.fax
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.qq
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.webchat
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String webchat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.mobile
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.tel
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer sortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Byte deletedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_contact.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.id
     *
     * @return the value of spring_contact.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.id
     *
     * @param id the value for spring_contact.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.company
     *
     * @return the value of spring_contact.company
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.company
     *
     * @param company the value for spring_contact.company
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.title
     *
     * @return the value of spring_contact.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.title
     *
     * @param title the value for spring_contact.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.username
     *
     * @return the value of spring_contact.username
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.username
     *
     * @param username the value for spring_contact.username
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.email
     *
     * @return the value of spring_contact.email
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.email
     *
     * @param email the value for spring_contact.email
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.web
     *
     * @return the value of spring_contact.web
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getWeb() {
        return web;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.web
     *
     * @param web the value for spring_contact.web
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setWeb(String web) {
        this.web = web;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.fax
     *
     * @return the value of spring_contact.fax
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.fax
     *
     * @param fax the value for spring_contact.fax
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.qq
     *
     * @return the value of spring_contact.qq
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.qq
     *
     * @param qq the value for spring_contact.qq
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.webchat
     *
     * @return the value of spring_contact.webchat
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getWebchat() {
        return webchat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.webchat
     *
     * @param webchat the value for spring_contact.webchat
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setWebchat(String webchat) {
        this.webchat = webchat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.mobile
     *
     * @return the value of spring_contact.mobile
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.mobile
     *
     * @param mobile the value for spring_contact.mobile
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.tel
     *
     * @return the value of spring_contact.tel
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.tel
     *
     * @param tel the value for spring_contact.tel
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.sort_code
     *
     * @return the value of spring_contact.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.sort_code
     *
     * @param sortCode the value for spring_contact.sort_code
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.deleted_status
     *
     * @return the value of spring_contact.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Byte getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.deleted_status
     *
     * @param deletedStatus the value for spring_contact.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDeletedStatus(Byte deletedStatus) {
        this.deletedStatus = deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.created_user_id
     *
     * @return the value of spring_contact.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.created_user_id
     *
     * @param createdUserId the value for spring_contact.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.created_by
     *
     * @return the value of spring_contact.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.created_by
     *
     * @param createdBy the value for spring_contact.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.created_on
     *
     * @return the value of spring_contact.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.created_on
     *
     * @param createdOn the value for spring_contact.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.created_ip
     *
     * @return the value of spring_contact.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.created_ip
     *
     * @param createdIp the value for spring_contact.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.updated_user_id
     *
     * @return the value of spring_contact.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.updated_user_id
     *
     * @param updatedUserId the value for spring_contact.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.updated_by
     *
     * @return the value of spring_contact.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.updated_by
     *
     * @param updatedBy the value for spring_contact.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.updated_on
     *
     * @return the value of spring_contact.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.updated_on
     *
     * @param updatedOn the value for spring_contact.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_contact.updated_ip
     *
     * @return the value of spring_contact.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_contact.updated_ip
     *
     * @param updatedIp the value for spring_contact.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }
}