package io.github.springsongs.domain;

import java.util.Date;

public class SpringSiteMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.from_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.from_user_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String fromUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.to_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.to_user_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String toUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.content
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private boolean deletedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_site_message.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.id
     *
     * @return the value of spring_site_message.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.id
     *
     * @param id the value for spring_site_message.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.from_user_id
     *
     * @return the value of spring_site_message.from_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.from_user_id
     *
     * @param fromUserId the value for spring_site_message.from_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.from_user_name
     *
     * @return the value of spring_site_message.from_user_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getFromUserName() {
        return fromUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.from_user_name
     *
     * @param fromUserName the value for spring_site_message.from_user_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setFromUserName(String fromUserName) {
        this.fromUserName = fromUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.to_user_id
     *
     * @return the value of spring_site_message.to_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.to_user_id
     *
     * @param toUserId the value for spring_site_message.to_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.to_user_name
     *
     * @return the value of spring_site_message.to_user_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getToUserName() {
        return toUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.to_user_name
     *
     * @param toUserName the value for spring_site_message.to_user_name
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setToUserName(String toUserName) {
        this.toUserName = toUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.title
     *
     * @return the value of spring_site_message.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.title
     *
     * @param title the value for spring_site_message.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.content
     *
     * @return the value of spring_site_message.content
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.content
     *
     * @param content the value for spring_site_message.content
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.status
     *
     * @return the value of spring_site_message.status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.status
     *
     * @param status the value for spring_site_message.status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.deleted_status
     *
     * @return the value of spring_site_message.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public boolean getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.deleted_status
     *
     * @param deletedStatus the value for spring_site_message.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDeletedStatus(boolean deletedStatus) {
        this.deletedStatus = deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.created_user_id
     *
     * @return the value of spring_site_message.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.created_user_id
     *
     * @param createdUserId the value for spring_site_message.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.created_by
     *
     * @return the value of spring_site_message.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.created_by
     *
     * @param createdBy the value for spring_site_message.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.created_on
     *
     * @return the value of spring_site_message.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.created_on
     *
     * @param createdOn the value for spring_site_message.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.created_ip
     *
     * @return the value of spring_site_message.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.created_ip
     *
     * @param createdIp the value for spring_site_message.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.updated_user_id
     *
     * @return the value of spring_site_message.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.updated_user_id
     *
     * @param updatedUserId the value for spring_site_message.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.updated_by
     *
     * @return the value of spring_site_message.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.updated_by
     *
     * @param updatedBy the value for spring_site_message.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.updated_on
     *
     * @return the value of spring_site_message.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.updated_on
     *
     * @param updatedOn the value for spring_site_message.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_site_message.updated_ip
     *
     * @return the value of spring_site_message.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_site_message.updated_ip
     *
     * @param updatedIp the value for spring_site_message.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }
}