package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringSiteMessage;
import io.github.springsongs.dto.SpringSiteMessageDTO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.pagehelper.Page;

public interface SpringSiteMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_message
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_message
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringSiteMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_message
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringSiteMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_message
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringSiteMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_message
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringSiteMessage record);

	List<SpringSiteMessage> listByPage(SpringSiteMessageDTO record);

	void setDelete(@Param("ids") List<String> ids);

	int countNotReadMessageByUserId(@Param("toUserId") String toUserId);
}