package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringAritlceDraft;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface SpringAritlceDraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_aritlce_draft
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_aritlce_draft
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringAritlceDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_aritlce_draft
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringAritlceDraft selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_aritlce_draft
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringAritlceDraft> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_aritlce_draft
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringAritlceDraft record);
}