package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringDistrict;
import io.github.springsongs.dto.SpringDistrictDTO;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SpringDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringDistrict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringDistrict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringDistrict record);

	List<SpringDistrict> listByPage(SpringDistrictDTO record);

	void setDelete(@Param("ids") List<Long> ids);

	List<SpringDistrict> listSpringDistrictByParentId(@Param("parentId") Long parentId);
}