package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringBlog;
import java.util.List;

public interface SpringBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringBlog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringBlog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringBlog record);
}