package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringFriendLink;
import io.github.springsongs.dto.SpringFriendLinkDTO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.pagehelper.Page;

public interface SpringFriendLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringFriendLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringFriendLink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringFriendLink> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_friend_link
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringFriendLink record);

	Page<SpringFriendLink> listByPage(SpringFriendLinkDTO record);

	void setDelete(@Param("ids") List<String> ids);
}