package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringBlogCategory;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SpringBlogCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringBlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringBlogCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringBlogCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_category
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringBlogCategory record);
}