package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringArticleComment;
import io.github.springsongs.dto.SpringArticleCommentDTO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SpringArticleCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringArticleComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringArticleComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringArticleComment record);

	List<SpringArticleComment> listByPage(SpringArticleCommentDTO springArticleCommentQuery);

	void setDelete(@Param("ids") List<String> ids);
}