package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringBlogComment;
import java.util.List;

public interface SpringBlogCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringBlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringBlogComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringBlogComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_blog_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringBlogComment record);
}