package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringOrganization;
import io.github.springsongs.dto.SpringOrganizationDTO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.pagehelper.Page;

public interface SpringOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_organization
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_organization
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_organization
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringOrganization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_organization
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringOrganization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_organization
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringOrganization record);

	Page<SpringOrganization> listByPage(SpringOrganizationDTO record);

	List<SpringOrganization> listOrganizationByParentId(@Param("id") String id);

	void setDelete(@Param("ids") List<String> ids);
}