package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringRole;
import io.github.springsongs.dto.SpringRoleDTO;

import java.util.List;

public interface SpringRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_role
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_role
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_role
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_role
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_role
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringRole record);

	List<SpringRole> listByPage(SpringRoleDTO springRoleQuery);

	List<SpringRole> findAllById(List<String> ids);

	void setDelete(List<String> ids);

	List<SpringRole> ListRoleByUserId(String userId);
}