package io.github.springsongs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import io.github.springsongs.domain.SpringResource;
import io.github.springsongs.dto.ResourceRoleDTO;
import io.github.springsongs.dto.SpringResourceDTO;

@Mapper
public interface SpringResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_resource
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_resource
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_resource
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_resource
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_resource
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringResource record);

	List<SpringResource> listByPage(SpringResourceDTO springResourceQuery);

	List<SpringResource> getInParentId(@Param("ids")List<String> ids);

	List<SpringResource> findAllById(@Param("ids")List<String> ids);

	void setDelete(@Param("ids")List<String> ids);

	List<SpringResource> listModuleByUserId(@Param("userId")String userId);

	List<SpringResource> getByParentId(@Param("parentId") String parentId,@Param("systemId")  String systemId);

	List<ResourceRoleDTO> listAllRoleModules(@Param("roleCodes")List<String> roleCodes);

	List<SpringResource> listAllResources(@Param("systemCode")String systemCode);
}