package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringDictionary;
import io.github.springsongs.dto.SpringDictionaryDTO;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SpringDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_dictionary
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_dictionary
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_dictionary
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringDictionary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_dictionary
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringDictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_dictionary
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringDictionary record);

	List<SpringDictionary> listByPage(SpringDictionaryDTO springDictionaryQuery);

	void setDelete(@Param("ids") List<String> ids);

	List<SpringDictionary> findInIds(@Param("ids") List<String> ids);
}