package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringAttachment;
import io.github.springsongs.dto.SpringAttachmentDTO;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SpringAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_attachment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_attachment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_attachment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringAttachment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_attachment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_attachment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringAttachment record);

	List<SpringAttachment> listByPage(SpringAttachmentDTO record);

	void setDelete(@Param("ids") List<String> ids);
}