package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringUser;
import io.github.springsongs.dto.SpringUserDTO;

import java.util.List;

import com.github.pagehelper.Page;

public interface SpringUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_user
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_user
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_user
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_user
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_user
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringUser record);

	SpringUser getByUserName(String userName);

	List<SpringUser> listByPage(SpringUserDTO springUserQuery);

	List<SpringUser> findAllById(List<String> ids);

	void setDelete(List<String> ids);

	List<SpringUser> listUserByIds(List<String> ids);

	Page<SpringUser> ListUsersByRoleId(String roleId);
}