package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringArticleComment;
import java.util.List;

public interface SpringArticleCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringArticleComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringArticleComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_article_comment
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringArticleComment record);
}