package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringDistrict;
import java.util.List;

public interface SpringDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringDistrict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringDistrict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_district
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringDistrict record);
}