package io.github.springsongs.mapper;

import io.github.springsongs.domain.SpringSiteNotice;
import io.github.springsongs.dto.SpringSiteNoticeDTO;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.github.pagehelper.Page;

@Mapper
public interface SpringSiteNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_notice
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_notice
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int insert(SpringSiteNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_notice
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    SpringSiteNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_notice
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    List<SpringSiteNotice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_site_notice
     *
     * @mbg.generated Mon Dec 14 16:39:39 CST 2020
     */
    int updateByPrimaryKey(SpringSiteNotice record);

	Page<SpringSiteNotice> listByPage(SpringSiteNoticeDTO record);

	void setDelete(@Param("ids") List<String> ids);
}