package io.github.springsongs.domain;

import java.util.Date;

public class SpringAritlceDraft {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.category_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.category_title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String categoryTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.color
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.tag
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.keyword
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.summary
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.author_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.author
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.author_url
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String authorUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.link
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.read_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.like_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.collect_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer collectCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.share_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer shareCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.top_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Byte topStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.hot_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Byte hotStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.featured
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Byte featured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.comment_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.sort_order
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.come_from
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String comeFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.come_from_link
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String comeFromLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Byte deletedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.version
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_aritlce_draft.contents
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String contents;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.id
     *
     * @return the value of spring_aritlce_draft.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.id
     *
     * @param id the value for spring_aritlce_draft.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.category_id
     *
     * @return the value of spring_aritlce_draft.category_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.category_id
     *
     * @param categoryId the value for spring_aritlce_draft.category_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.category_title
     *
     * @return the value of spring_aritlce_draft.category_title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCategoryTitle() {
        return categoryTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.category_title
     *
     * @param categoryTitle the value for spring_aritlce_draft.category_title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCategoryTitle(String categoryTitle) {
        this.categoryTitle = categoryTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.color
     *
     * @return the value of spring_aritlce_draft.color
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.color
     *
     * @param color the value for spring_aritlce_draft.color
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.tag
     *
     * @return the value of spring_aritlce_draft.tag
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.tag
     *
     * @param tag the value for spring_aritlce_draft.tag
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.keyword
     *
     * @return the value of spring_aritlce_draft.keyword
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.keyword
     *
     * @param keyword the value for spring_aritlce_draft.keyword
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.title
     *
     * @return the value of spring_aritlce_draft.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.title
     *
     * @param title the value for spring_aritlce_draft.title
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.summary
     *
     * @return the value of spring_aritlce_draft.summary
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.summary
     *
     * @param summary the value for spring_aritlce_draft.summary
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.author_id
     *
     * @return the value of spring_aritlce_draft.author_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.author_id
     *
     * @param authorId the value for spring_aritlce_draft.author_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.author
     *
     * @return the value of spring_aritlce_draft.author
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.author
     *
     * @param author the value for spring_aritlce_draft.author
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.author_url
     *
     * @return the value of spring_aritlce_draft.author_url
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getAuthorUrl() {
        return authorUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.author_url
     *
     * @param authorUrl the value for spring_aritlce_draft.author_url
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setAuthorUrl(String authorUrl) {
        this.authorUrl = authorUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.status
     *
     * @return the value of spring_aritlce_draft.status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.status
     *
     * @param status the value for spring_aritlce_draft.status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.link
     *
     * @return the value of spring_aritlce_draft.link
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.link
     *
     * @param link the value for spring_aritlce_draft.link
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.read_count
     *
     * @return the value of spring_aritlce_draft.read_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.read_count
     *
     * @param readCount the value for spring_aritlce_draft.read_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.like_count
     *
     * @return the value of spring_aritlce_draft.like_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.like_count
     *
     * @param likeCount the value for spring_aritlce_draft.like_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.collect_count
     *
     * @return the value of spring_aritlce_draft.collect_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.collect_count
     *
     * @param collectCount the value for spring_aritlce_draft.collect_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCollectCount(Integer collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.share_count
     *
     * @return the value of spring_aritlce_draft.share_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getShareCount() {
        return shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.share_count
     *
     * @param shareCount the value for spring_aritlce_draft.share_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setShareCount(Integer shareCount) {
        this.shareCount = shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.top_status
     *
     * @return the value of spring_aritlce_draft.top_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Byte getTopStatus() {
        return topStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.top_status
     *
     * @param topStatus the value for spring_aritlce_draft.top_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setTopStatus(Byte topStatus) {
        this.topStatus = topStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.hot_status
     *
     * @return the value of spring_aritlce_draft.hot_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Byte getHotStatus() {
        return hotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.hot_status
     *
     * @param hotStatus the value for spring_aritlce_draft.hot_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setHotStatus(Byte hotStatus) {
        this.hotStatus = hotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.featured
     *
     * @return the value of spring_aritlce_draft.featured
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Byte getFeatured() {
        return featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.featured
     *
     * @param featured the value for spring_aritlce_draft.featured
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setFeatured(Byte featured) {
        this.featured = featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.comment_count
     *
     * @return the value of spring_aritlce_draft.comment_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.comment_count
     *
     * @param commentCount the value for spring_aritlce_draft.comment_count
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.sort_order
     *
     * @return the value of spring_aritlce_draft.sort_order
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.sort_order
     *
     * @param sortOrder the value for spring_aritlce_draft.sort_order
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.come_from
     *
     * @return the value of spring_aritlce_draft.come_from
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getComeFrom() {
        return comeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.come_from
     *
     * @param comeFrom the value for spring_aritlce_draft.come_from
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setComeFrom(String comeFrom) {
        this.comeFrom = comeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.come_from_link
     *
     * @return the value of spring_aritlce_draft.come_from_link
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getComeFromLink() {
        return comeFromLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.come_from_link
     *
     * @param comeFromLink the value for spring_aritlce_draft.come_from_link
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setComeFromLink(String comeFromLink) {
        this.comeFromLink = comeFromLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.deleted_status
     *
     * @return the value of spring_aritlce_draft.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Byte getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.deleted_status
     *
     * @param deletedStatus the value for spring_aritlce_draft.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setDeletedStatus(Byte deletedStatus) {
        this.deletedStatus = deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.created_user_id
     *
     * @return the value of spring_aritlce_draft.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.created_user_id
     *
     * @param createdUserId the value for spring_aritlce_draft.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.created_by
     *
     * @return the value of spring_aritlce_draft.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.created_by
     *
     * @param createdBy the value for spring_aritlce_draft.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.created_on
     *
     * @return the value of spring_aritlce_draft.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.created_on
     *
     * @param createdOn the value for spring_aritlce_draft.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.created_ip
     *
     * @return the value of spring_aritlce_draft.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.created_ip
     *
     * @param createdIp the value for spring_aritlce_draft.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.updated_user_id
     *
     * @return the value of spring_aritlce_draft.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.updated_user_id
     *
     * @param updatedUserId the value for spring_aritlce_draft.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.updated_by
     *
     * @return the value of spring_aritlce_draft.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.updated_by
     *
     * @param updatedBy the value for spring_aritlce_draft.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.updated_on
     *
     * @return the value of spring_aritlce_draft.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.updated_on
     *
     * @param updatedOn the value for spring_aritlce_draft.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.updated_ip
     *
     * @return the value of spring_aritlce_draft.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.updated_ip
     *
     * @param updatedIp the value for spring_aritlce_draft.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.version
     *
     * @return the value of spring_aritlce_draft.version
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.version
     *
     * @param version the value for spring_aritlce_draft.version
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_aritlce_draft.contents
     *
     * @return the value of spring_aritlce_draft.contents
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_aritlce_draft.contents
     *
     * @param contents the value for spring_aritlce_draft.contents
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setContents(String contents) {
        this.contents = contents;
    }
}