package io.github.springsongs.domain;

import java.util.Date;

public class SpringUserSecurity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.pwd
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_user_security.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.id
     *
     * @return the value of spring_user_security.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.id
     *
     * @param id the value for spring_user_security.id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.user_id
     *
     * @return the value of spring_user_security.user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.user_id
     *
     * @param userId the value for spring_user_security.user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.pwd
     *
     * @return the value of spring_user_security.pwd
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.pwd
     *
     * @param pwd the value for spring_user_security.pwd
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.created_user_id
     *
     * @return the value of spring_user_security.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.created_user_id
     *
     * @param createdUserId the value for spring_user_security.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.created_by
     *
     * @return the value of spring_user_security.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.created_by
     *
     * @param createdBy the value for spring_user_security.created_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.created_on
     *
     * @return the value of spring_user_security.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.created_on
     *
     * @param createdOn the value for spring_user_security.created_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.created_ip
     *
     * @return the value of spring_user_security.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.created_ip
     *
     * @param createdIp the value for spring_user_security.created_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.updated_user_id
     *
     * @return the value of spring_user_security.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.updated_user_id
     *
     * @param updatedUserId the value for spring_user_security.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.updated_by
     *
     * @return the value of spring_user_security.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.updated_by
     *
     * @param updatedBy the value for spring_user_security.updated_by
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.updated_on
     *
     * @return the value of spring_user_security.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.updated_on
     *
     * @param updatedOn the value for spring_user_security.updated_on
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_user_security.updated_ip
     *
     * @return the value of spring_user_security.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_user_security.updated_ip
     *
     * @param updatedIp the value for spring_user_security.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:38:23 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }
}