package io.github.springsongs.domain;

import java.util.Date;

public class SpringJob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.group_code
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String groupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.group_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String groupTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.task_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String taskTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.task_class_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String taskClassTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.cron_Expression
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.status
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.remark
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.created_by
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.created_on
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.created_ip
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.updated_by
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.updated_on
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_job.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.id
     *
     * @return the value of spring_job.id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.id
     *
     * @param id the value for spring_job.id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.group_code
     *
     * @return the value of spring_job.group_code
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.group_code
     *
     * @param groupCode the value for spring_job.group_code
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.group_title
     *
     * @return the value of spring_job.group_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getGroupTitle() {
        return groupTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.group_title
     *
     * @param groupTitle the value for spring_job.group_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setGroupTitle(String groupTitle) {
        this.groupTitle = groupTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.task_title
     *
     * @return the value of spring_job.task_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getTaskTitle() {
        return taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.task_title
     *
     * @param taskTitle the value for spring_job.task_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.task_class_title
     *
     * @return the value of spring_job.task_class_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getTaskClassTitle() {
        return taskClassTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.task_class_title
     *
     * @param taskClassTitle the value for spring_job.task_class_title
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setTaskClassTitle(String taskClassTitle) {
        this.taskClassTitle = taskClassTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.cron_Expression
     *
     * @return the value of spring_job.cron_Expression
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.cron_Expression
     *
     * @param cronExpression the value for spring_job.cron_Expression
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.status
     *
     * @return the value of spring_job.status
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.status
     *
     * @param status the value for spring_job.status
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.remark
     *
     * @return the value of spring_job.remark
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.remark
     *
     * @param remark the value for spring_job.remark
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.created_user_id
     *
     * @return the value of spring_job.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.created_user_id
     *
     * @param createdUserId the value for spring_job.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.created_by
     *
     * @return the value of spring_job.created_by
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.created_by
     *
     * @param createdBy the value for spring_job.created_by
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.created_on
     *
     * @return the value of spring_job.created_on
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.created_on
     *
     * @param createdOn the value for spring_job.created_on
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.created_ip
     *
     * @return the value of spring_job.created_ip
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.created_ip
     *
     * @param createdIp the value for spring_job.created_ip
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.updated_user_id
     *
     * @return the value of spring_job.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.updated_user_id
     *
     * @param updatedUserId the value for spring_job.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.updated_by
     *
     * @return the value of spring_job.updated_by
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.updated_by
     *
     * @param updatedBy the value for spring_job.updated_by
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.updated_on
     *
     * @return the value of spring_job.updated_on
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.updated_on
     *
     * @param updatedOn the value for spring_job.updated_on
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_job.updated_ip
     *
     * @return the value of spring_job.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_job.updated_ip
     *
     * @param updatedIp the value for spring_job.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:28:43 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }
}