package io.github.springsongs.domain;

import java.util.Date;

public class SpringActVacation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.process_instance_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String processInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.proc_def_key
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String procDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.true_name
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String trueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.title
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.vacation_type
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String vacationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.reason
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.process_status
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Short processStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.submit_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Date submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.start_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.end_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Byte deletedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.created_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.created_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.created_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.updated_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.updated_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.id
     *
     * @return the value of spring_act_vacation.id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.id
     *
     * @param id the value for spring_act_vacation.id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.process_instance_id
     *
     * @return the value of spring_act_vacation.process_instance_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.process_instance_id
     *
     * @param processInstanceId the value for spring_act_vacation.process_instance_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.proc_def_key
     *
     * @return the value of spring_act_vacation.proc_def_key
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getProcDefKey() {
        return procDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.proc_def_key
     *
     * @param procDefKey the value for spring_act_vacation.proc_def_key
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setProcDefKey(String procDefKey) {
        this.procDefKey = procDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.user_id
     *
     * @return the value of spring_act_vacation.user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.user_id
     *
     * @param userId the value for spring_act_vacation.user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.true_name
     *
     * @return the value of spring_act_vacation.true_name
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.true_name
     *
     * @param trueName the value for spring_act_vacation.true_name
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.title
     *
     * @return the value of spring_act_vacation.title
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.title
     *
     * @param title the value for spring_act_vacation.title
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.vacation_type
     *
     * @return the value of spring_act_vacation.vacation_type
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getVacationType() {
        return vacationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.vacation_type
     *
     * @param vacationType the value for spring_act_vacation.vacation_type
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setVacationType(String vacationType) {
        this.vacationType = vacationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.reason
     *
     * @return the value of spring_act_vacation.reason
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.reason
     *
     * @param reason the value for spring_act_vacation.reason
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.time
     *
     * @return the value of spring_act_vacation.time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.time
     *
     * @param time the value for spring_act_vacation.time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.process_status
     *
     * @return the value of spring_act_vacation.process_status
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Short getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.process_status
     *
     * @param processStatus the value for spring_act_vacation.process_status
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setProcessStatus(Short processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.submit_time
     *
     * @return the value of spring_act_vacation.submit_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.submit_time
     *
     * @param submitTime the value for spring_act_vacation.submit_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.start_time
     *
     * @return the value of spring_act_vacation.start_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.start_time
     *
     * @param startTime the value for spring_act_vacation.start_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.end_time
     *
     * @return the value of spring_act_vacation.end_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.end_time
     *
     * @param endTime the value for spring_act_vacation.end_time
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.deleted_status
     *
     * @return the value of spring_act_vacation.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Byte getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.deleted_status
     *
     * @param deletedStatus the value for spring_act_vacation.deleted_status
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setDeletedStatus(Byte deletedStatus) {
        this.deletedStatus = deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.created_user_id
     *
     * @return the value of spring_act_vacation.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.created_user_id
     *
     * @param createdUserId the value for spring_act_vacation.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.created_by
     *
     * @return the value of spring_act_vacation.created_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.created_by
     *
     * @param createdBy the value for spring_act_vacation.created_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.created_on
     *
     * @return the value of spring_act_vacation.created_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.created_on
     *
     * @param createdOn the value for spring_act_vacation.created_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.created_ip
     *
     * @return the value of spring_act_vacation.created_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.created_ip
     *
     * @param createdIp the value for spring_act_vacation.created_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.updated_user_id
     *
     * @return the value of spring_act_vacation.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.updated_user_id
     *
     * @param updatedUserId the value for spring_act_vacation.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.updated_by
     *
     * @return the value of spring_act_vacation.updated_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.updated_by
     *
     * @param updatedBy the value for spring_act_vacation.updated_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.updated_on
     *
     * @return the value of spring_act_vacation.updated_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.updated_on
     *
     * @param updatedOn the value for spring_act_vacation.updated_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation.updated_ip
     *
     * @return the value of spring_act_vacation.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation.updated_ip
     *
     * @param updatedIp the value for spring_act_vacation.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }
}