package io.github.springsongs.domain;

import java.util.Date;

public class SpringActVacationApprove {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.vacation_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String vacationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.process_instance_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String processInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.task_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.result
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Short result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.remark
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.true_name
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String trueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.created_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.created_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.created_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String createdIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.updated_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.updated_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_act_vacation_approve.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    private String updatedIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.id
     *
     * @return the value of spring_act_vacation_approve.id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.id
     *
     * @param id the value for spring_act_vacation_approve.id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.vacation_id
     *
     * @return the value of spring_act_vacation_approve.vacation_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getVacationId() {
        return vacationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.vacation_id
     *
     * @param vacationId the value for spring_act_vacation_approve.vacation_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setVacationId(String vacationId) {
        this.vacationId = vacationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.process_instance_id
     *
     * @return the value of spring_act_vacation_approve.process_instance_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.process_instance_id
     *
     * @param processInstanceId the value for spring_act_vacation_approve.process_instance_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.task_id
     *
     * @return the value of spring_act_vacation_approve.task_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.task_id
     *
     * @param taskId the value for spring_act_vacation_approve.task_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.user_id
     *
     * @return the value of spring_act_vacation_approve.user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.user_id
     *
     * @param userId the value for spring_act_vacation_approve.user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.result
     *
     * @return the value of spring_act_vacation_approve.result
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Short getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.result
     *
     * @param result the value for spring_act_vacation_approve.result
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setResult(Short result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.remark
     *
     * @return the value of spring_act_vacation_approve.remark
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.remark
     *
     * @param remark the value for spring_act_vacation_approve.remark
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.true_name
     *
     * @return the value of spring_act_vacation_approve.true_name
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.true_name
     *
     * @param trueName the value for spring_act_vacation_approve.true_name
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.created_user_id
     *
     * @return the value of spring_act_vacation_approve.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.created_user_id
     *
     * @param createdUserId the value for spring_act_vacation_approve.created_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.created_by
     *
     * @return the value of spring_act_vacation_approve.created_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.created_by
     *
     * @param createdBy the value for spring_act_vacation_approve.created_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.created_on
     *
     * @return the value of spring_act_vacation_approve.created_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.created_on
     *
     * @param createdOn the value for spring_act_vacation_approve.created_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.created_ip
     *
     * @return the value of spring_act_vacation_approve.created_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getCreatedIp() {
        return createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.created_ip
     *
     * @param createdIp the value for spring_act_vacation_approve.created_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.updated_user_id
     *
     * @return the value of spring_act_vacation_approve.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.updated_user_id
     *
     * @param updatedUserId the value for spring_act_vacation_approve.updated_user_id
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.updated_by
     *
     * @return the value of spring_act_vacation_approve.updated_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.updated_by
     *
     * @param updatedBy the value for spring_act_vacation_approve.updated_by
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.updated_on
     *
     * @return the value of spring_act_vacation_approve.updated_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.updated_on
     *
     * @param updatedOn the value for spring_act_vacation_approve.updated_on
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_act_vacation_approve.updated_ip
     *
     * @return the value of spring_act_vacation_approve.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public String getUpdatedIp() {
        return updatedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_act_vacation_approve.updated_ip
     *
     * @param updatedIp the value for spring_act_vacation_approve.updated_ip
     *
     * @mbg.generated Mon Dec 14 16:20:59 CST 2020
     */
    public void setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
    }
}